spring.application.name=WaterAndElectricityBillingManagementSystem

# Database Configuration
spring.datasource.url=jdbc:mysql://sql7.freesqldatabase.com:3306/sql7824272?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=sql7824272
spring.datasource.password=AthLcul4qA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Web Configuration
server.port=${PORT:8080}

# JWT Configuration
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=86400000

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:ihirweraissa@gmail.com}
spring.mail.password=${MAIL_PASSWORD:fxyg dowy gwut uwat}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

